[workspace]
members = ["keikaku", "keikaku_cli", "keikaku_ui"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
# System
tokio = { version = "1.48", features = ["full"] }
async-trait = "0.1"
futures = "0.3"
indicatif = "0.18"
base64 = "0.22"
toml = "0.9"
tempfile = "3.23"
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json"] }
ordered-float = "5.1"
zip = "6.0"
rusqlite = { version = "0.37", features = ["bundled"] }
regex = "1.12"
libz-sys = "*"
flate2 = { version = "*", features = ["zlib"] }
imp = { version = "0.1" }

# Logging
tracing = "0.1"

# OpenAI
async-openai = "0.30"

# Domain
ulid = { version = "1.2", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["std", "clock", "serde"] }
rand = "0.9"

# Japan
fsrs = "5.2"
autoruby = { version = "0.5", features = ["integrated"] }
wana_kana = "4"

# Machine Learning
hf-hub = "0.4"
intel-mkl-src = { version = "0.8" }
candle-core = { version = "0.9.2-alpha.1" }
candle-transformers = { version = "0.9.2-alpha.1" }
candle-nn = { version = "0.9.2-alpha.1" }
text-embeddings-backend-core = { git = "https://github.com/huggingface/text-embeddings-inference.git", version = "1.8.3" }
text-embeddings-backend-candle = { git = "https://github.com/huggingface/text-embeddings-inference.git", version = "1.8.3" }
tokenizers = { version = "0.22.1", default-features = false, features = [
    "onig",
    "esaxx_fast",
] }

# CLI utilities
clap = { version = "4.5", features = ["derive"] }

# TUI
ratatui = "0.29"
crossterm = "0.29"

# UI
dioxus = { version = "0.7", features = ["router"] }

# Testing
rstest = "0.26"
