[application]
name = "keikaku"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Keikaku"

[web.watcher]
reload_html = true
watch_path = ["keikaku_ui", "keikaku", "assets"]

[bundle]
identifier = "new.uwuwu.keikaku"
publisher = "yurvon_screamo"
