[application]

[web.app]
title = "keikaku"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[bundle]
identifier = "net.uwuwu.keikaku"
publisher = "uwuwu.net"
icon = [
    "assets/icons/icon.png",
    "assets/icons/32x32.png",
    "assets/icons/64x64.png",
    "assets/icons/128x128.png",
    "assets/icons/128x128@2x.png",
    "assets/icons/icon.icns",
    "assets/icons/icon.ico",
]
